/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.TabuleiroControl;
import Model.Tabuleiro;
import java.awt.Point;
import javax.swing.JLabel;

/**
 *
 * @author paabl
 */
public class PanelTabuleiroViewAntigo extends javax.swing.JFrame {

    /**
     * Creates new form TabuleiroView
     */
    TabuleiroControl tbControl;
    JLabel[] pecas;
    Point[] caminhoVerde;
   
    public PanelTabuleiroViewAntigo() {
        
        initComponents();
        //tbControl = new TabuleiroControl();
        pecas = new JLabel[]{
            jLabelPeaoGreen2,
            jLabelPeaoRed2,
            jLabelPeaoBlue2,
            jLabelPeaoYellow1
        };
        
        caminhoVerde = new Point[]{
            new Point(10,290),new Point(80,290),new Point(150,290),new Point(220,290),new Point(290,290),new Point(360,290),
            new Point(430,250),new Point(430,200),new Point(430,150),new Point(430,100),new Point(430,50),new Point(430,0),
            new Point(500,0),new Point(570,50),new Point(430,100),new Point(430,150),new Point(430,200),new Point(430,250), 
        };
        
        //this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jLabelPeaoRed1 = new javax.swing.JLabel();
        jLabelPeaoGreen1 = new javax.swing.JLabel();
        jLabelPeaoBlue1 = new javax.swing.JLabel();
        jLabelPeaoYellow2 = new javax.swing.JLabel();
        jLabelPeaoRed2 = new javax.swing.JLabel();
        jLabelPeaoGreen2 = new javax.swing.JLabel();
        jLabelPeaoYellow1 = new javax.swing.JLabel();
        jLabelPeaoBlue2 = new javax.swing.JLabel();
        jLabelTabuleiro = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jBtnLançar = new javax.swing.JButton();
        jBtnMover = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelDado1 = new javax.swing.JLabel();
        jLabelDado2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(240, 240, 240));

        jLabelPeaoRed1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/peçavermelha1.png.png"))); // NOI18N
        desktopPane.add(jLabelPeaoRed1);
        jLabelPeaoRed1.setBounds(800, 120, 30, 42);

        jLabelPeaoGreen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-green-th.png"))); // NOI18N
        desktopPane.add(jLabelPeaoGreen1);
        jLabelPeaoGreen1.setBounds(190, 120, 23, 32);

        jLabelPeaoBlue1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-peacock-blue-hi.png"))); // NOI18N
        desktopPane.add(jLabelPeaoBlue1);
        jLabelPeaoBlue1.setBounds(800, 550, 30, 42);

        jLabelPeaoYellow2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-mustard-yellow-th.png"))); // NOI18N
        desktopPane.add(jLabelPeaoYellow2);
        jLabelPeaoYellow2.setBounds(190, 550, 30, 42);

        jLabelPeaoRed2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/peçavermelha1.png.png"))); // NOI18N
        jLabelPeaoRed2.setText("1");
        desktopPane.add(jLabelPeaoRed2);
        jLabelPeaoRed2.setBounds(570, 10, 40, 42);

        jLabelPeaoGreen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-green-th.png"))); // NOI18N
        jLabelPeaoGreen2.setText("0");
        desktopPane.add(jLabelPeaoGreen2);
        jLabelPeaoGreen2.setBounds(10, 290, 30, 32);

        jLabelPeaoYellow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-mustard-yellow-th.png"))); // NOI18N
        jLabelPeaoYellow1.setText("3");
        desktopPane.add(jLabelPeaoYellow1);
        jLabelPeaoYellow1.setBounds(430, 670, 40, 42);

        jLabelPeaoBlue2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-peacock-blue-hi.png"))); // NOI18N
        jLabelPeaoBlue2.setText("2");
        desktopPane.add(jLabelPeaoBlue2);
        jLabelPeaoBlue2.setBounds(970, 390, 40, 42);

        jLabelTabuleiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageTabuleiro/5e78c6204279850aff43a1166d2ee621.gif"))); // NOI18N
        desktopPane.add(jLabelTabuleiro);
        jLabelTabuleiro.setBounds(14, 0, 1010, 720);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opções de jogo"));

        jBtnLançar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageDado/dados.png"))); // NOI18N
        jBtnLançar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLançarActionPerformed(evt);
            }
        });

        jBtnMover.setText("Mover");
        jBtnMover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMoverActionPerformed(evt);
            }
        });

        jLabel1.setText("Dado um :");

        jLabel2.setText("Dado dois :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jBtnLançar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDado1)
                            .addComponent(jLabelDado2))))
                .addGap(25, 25, 25))
            .addComponent(jBtnMover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnLançar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDado1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDado2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnMover)
                .addGap(0, 575, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1025, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jBtnLançarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLançarActionPerformed
        
        tbControl.jogar();
        
        jLabelDado1.setText(""+Tabuleiro.numD1());
        jLabelDado2.setText(""+Tabuleiro.numD2());
        jBtnMover.setText("Mover "+(Tabuleiro.numD1()+Tabuleiro.numD2())+" casas");
  
    }//GEN-LAST:event_jBtnLançarActionPerformed

    int p = 0;
    private void jBtnMoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMoverActionPerformed
      
       int pecaDaVez = tbControl.jogadorDaVez-1;
        
       if(pecaDaVez > 3)
           pecaDaVez = 0;
       
       
//       int x,y;
//       x = pecas[pecaDaVez].getLocation().x;
//       y = pecas[pecaDaVez].getLocation().y;
       
       
       if(pecaDaVez == 0){
           int casa = (Tabuleiro.numD1()+Tabuleiro.numD2())-1;
           p += casa;
           pecas[pecaDaVez].setLocation(caminhoVerde[p]);
           System.out.print(p+" ");
           //casaVerdeAnterior = casa;
       }
       
       
        //jLabel4.setLocation(x+5, y);
        
        
        //Se for a peça verde
//        if(pecaDaVez == 0){
//            int casa = tbControl.jogadores[pecaDaVez+1].getPeca().getNumCasa();
//            pecas[pecaDaVez].setLocation(caminhoVerde[casa]);
//        }
            
        
//       for(int i = 0; i < (Tabuleiro.numD1()+Tabuleiro.numD2()); i++){
//           x += 70;
//           pecas[pecaDaVez].setLocation(x, y);     
//           
//       }      
    }//GEN-LAST:event_jBtnMoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelTabuleiroViewAntigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelTabuleiroViewAntigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelTabuleiroViewAntigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelTabuleiroViewAntigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelTabuleiroViewAntigo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton jBtnLançar;
    private javax.swing.JButton jBtnMover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDado1;
    private javax.swing.JLabel jLabelDado2;
    private javax.swing.JLabel jLabelPeaoBlue1;
    private javax.swing.JLabel jLabelPeaoBlue2;
    private javax.swing.JLabel jLabelPeaoGreen1;
    private javax.swing.JLabel jLabelPeaoGreen2;
    private javax.swing.JLabel jLabelPeaoRed1;
    private javax.swing.JLabel jLabelPeaoRed2;
    private javax.swing.JLabel jLabelPeaoYellow1;
    private javax.swing.JLabel jLabelPeaoYellow2;
    private javax.swing.JLabel jLabelTabuleiro;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
