/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.TabuleiroControl;
import javax.swing.JOptionPane;

/**
 *
 * @author paabl
 */
public class PanelTabuleiroView extends javax.swing.JPanel {

    /**
     * Creates new form TAB
     */
    
    TabuleiroControl control;
    public PanelTabuleiroView() {
        control = new TabuleiroControl(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelUser1 = new javax.swing.JLabel();
        jLabelUser3 = new javax.swing.JLabel();
        jLabelUser4 = new javax.swing.JLabel();
        jLabelUser2 = new javax.swing.JLabel();
        jLabelPeaoYellow4 = new javax.swing.JLabel();
        jLabelPeaoBlue4 = new javax.swing.JLabel();
        jLabelPeaoBlue2 = new javax.swing.JLabel();
        jLabelPeaoBlue3 = new javax.swing.JLabel();
        jLabelPeaoYellow3 = new javax.swing.JLabel();
        jLabelPeaoBlue1 = new javax.swing.JLabel();
        jLabelPeaoYellow2 = new javax.swing.JLabel();
        jLabelDados = new javax.swing.JLabel();
        jLabelPeaoYellow1 = new javax.swing.JLabel();
        jLabelPeaoRed3 = new javax.swing.JLabel();
        jLabelPeaoRed4 = new javax.swing.JLabel();
        jLabelPeaoGreen2 = new javax.swing.JLabel();
        jLabelPeaoRed2 = new javax.swing.JLabel();
        jLabelPeaoRed1 = new javax.swing.JLabel();
        jLabelPeaoGreen4 = new javax.swing.JLabel();
        jLabelPeaoGreen3 = new javax.swing.JLabel();
        jLabelPeaoGreen1 = new javax.swing.JLabel();
        jLabelTabuleiero = new javax.swing.JLabel();
        jLabelCircleYellow = new javax.swing.JLabel();
        jLabelCircleBlue = new javax.swing.JLabel();
        jLabelCircleGreen = new javax.swing.JLabel();
        jLabelCircleRed = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonSair = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 253, 165));
        jPanel1.setLayout(null);

        jLabelUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAvatars/avatar2.png"))); // NOI18N
        jLabelUser1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jPanel1.add(jLabelUser1);
        jLabelUser1.setBounds(140, 390, 70, 80);

        jLabelUser3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAvatars/avatar4.png"))); // NOI18N
        jLabelUser3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jPanel1.add(jLabelUser3);
        jLabelUser3.setBounds(1030, 400, 70, 80);

        jLabelUser4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAvatars/avatar3.png"))); // NOI18N
        jLabelUser4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jPanel1.add(jLabelUser4);
        jLabelUser4.setBounds(1020, 30, 70, 80);

        jLabelUser2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAvatars/avatar1.png"))); // NOI18N
        jLabelUser2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jPanel1.add(jLabelUser2);
        jLabelUser2.setBounds(130, 40, 70, 70);

        jLabelPeaoYellow4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-yellow.png"))); // NOI18N
        jPanel1.add(jLabelPeaoYellow4);
        jLabelPeaoYellow4.setBounds(560, 480, 23, 32);

        jLabelPeaoBlue4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-blue.png"))); // NOI18N
        jPanel1.add(jLabelPeaoBlue4);
        jLabelPeaoBlue4.setBounds(630, 410, 23, 32);

        jLabelPeaoBlue2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-blue.png"))); // NOI18N
        jPanel1.add(jLabelPeaoBlue2);
        jLabelPeaoBlue2.setBounds(850, 470, 23, 32);

        jLabelPeaoBlue3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-blue.png"))); // NOI18N
        jPanel1.add(jLabelPeaoBlue3);
        jLabelPeaoBlue3.setBounds(790, 470, 23, 32);

        jLabelPeaoYellow3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-yellow.png"))); // NOI18N
        jPanel1.add(jLabelPeaoYellow3);
        jLabelPeaoYellow3.setBounds(440, 570, 23, 32);

        jLabelPeaoBlue1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-blue.png"))); // NOI18N
        jPanel1.add(jLabelPeaoBlue1);
        jLabelPeaoBlue1.setBounds(820, 430, 23, 32);

        jLabelPeaoYellow2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-yellow.png"))); // NOI18N
        jPanel1.add(jLabelPeaoYellow2);
        jLabelPeaoYellow2.setBounds(410, 530, 23, 32);

        jLabelDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageViews/dado.png"))); // NOI18N
        jLabelDados.setToolTipText("");
        jPanel1.add(jLabelDados);
        jLabelDados.setBounds(120, 590, 115, 87);

        jLabelPeaoYellow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-yellow.png"))); // NOI18N
        jPanel1.add(jLabelPeaoYellow1);
        jLabelPeaoYellow1.setBounds(440, 500, 23, 32);

        jLabelPeaoRed3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-red-th4.png"))); // NOI18N
        jPanel1.add(jLabelPeaoRed3);
        jLabelPeaoRed3.setBounds(790, 90, 23, 40);

        jLabelPeaoRed4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-red-th4.png"))); // NOI18N
        jPanel1.add(jLabelPeaoRed4);
        jLabelPeaoRed4.setBounds(630, 70, 23, 40);

        jLabelPeaoGreen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-green.png"))); // NOI18N
        jPanel1.add(jLabelPeaoGreen2);
        jLabelPeaoGreen2.setBounds(340, 160, 30, 40);

        jLabelPeaoRed2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-red-th4.png"))); // NOI18N
        jPanel1.add(jLabelPeaoRed2);
        jLabelPeaoRed2.setBounds(710, 90, 23, 40);

        jLabelPeaoRed1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-red-th4.png"))); // NOI18N
        jPanel1.add(jLabelPeaoRed1);
        jLabelPeaoRed1.setBounds(750, 50, 23, 40);

        jLabelPeaoGreen4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-green.png"))); // NOI18N
        jPanel1.add(jLabelPeaoGreen4);
        jLabelPeaoGreen4.setBounds(360, 270, 30, 40);

        jLabelPeaoGreen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-green.png"))); // NOI18N
        jPanel1.add(jLabelPeaoGreen3);
        jLabelPeaoGreen3.setBounds(410, 150, 30, 40);

        jLabelPeaoGreen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-green.png"))); // NOI18N
        jPanel1.add(jLabelPeaoGreen1);
        jLabelPeaoGreen1.setBounds(370, 120, 30, 40);

        jLabelTabuleiero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageViews/tabu.png"))); // NOI18N
        jLabelTabuleiero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(jLabelTabuleiero);
        jLabelTabuleiero.setBounds(280, 10, 656, 653);

        jLabelCircleYellow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageViews/yellow-circle-design-hi.png"))); // NOI18N
        jPanel1.add(jLabelCircleYellow);
        jLabelCircleYellow.setBounds(10, 380, 350, 345);

        jLabelCircleBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageViews/blue-circle-design-hi.png"))); // NOI18N
        jPanel1.add(jLabelCircleBlue);
        jLabelCircleBlue.setBounds(890, 380, 350, 345);

        jLabelCircleGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageViews/green-circle-design-hi.png"))); // NOI18N
        jPanel1.add(jLabelCircleGreen);
        jLabelCircleGreen.setBounds(10, 21, 350, 345);

        jLabelCircleRed.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.activeTitleGradient"));
        jLabelCircleRed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageViews/red-circle-design-hi.png"))); // NOI18N
        jPanel1.add(jLabelCircleRed);
        jLabelCircleRed.setBounds(870, 20, 350, 345);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 253, 165));

        jButtonSair.setBackground(new java.awt.Color(255, 253, 165));
        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageViews/logoutDOOR.png"))); // NOI18N
        jButtonSair.setBorder(null);
        jButtonSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(1304, Short.MAX_VALUE)
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(255, 253, 165));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 855, Short.MAX_VALUE)
        );

        add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel5.setBackground(new java.awt.Color(255, 253, 165));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 855, Short.MAX_VALUE)
        );

        add(jPanel5, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        
        int reply = JOptionPane.showConfirmDialog(null, "Tem certeza que você deseja sair", "Fazer logout", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
          control.viewAnterior();
        }
    

    }//GEN-LAST:event_jButtonSairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelCircleBlue;
    private javax.swing.JLabel jLabelCircleGreen;
    private javax.swing.JLabel jLabelCircleRed;
    private javax.swing.JLabel jLabelCircleYellow;
    private javax.swing.JLabel jLabelDados;
    private javax.swing.JLabel jLabelPeaoBlue1;
    private javax.swing.JLabel jLabelPeaoBlue2;
    private javax.swing.JLabel jLabelPeaoBlue3;
    private javax.swing.JLabel jLabelPeaoBlue4;
    private javax.swing.JLabel jLabelPeaoGreen1;
    private javax.swing.JLabel jLabelPeaoGreen2;
    private javax.swing.JLabel jLabelPeaoGreen3;
    private javax.swing.JLabel jLabelPeaoGreen4;
    private javax.swing.JLabel jLabelPeaoRed1;
    private javax.swing.JLabel jLabelPeaoRed2;
    private javax.swing.JLabel jLabelPeaoRed3;
    private javax.swing.JLabel jLabelPeaoRed4;
    private javax.swing.JLabel jLabelPeaoYellow1;
    private javax.swing.JLabel jLabelPeaoYellow2;
    private javax.swing.JLabel jLabelPeaoYellow3;
    private javax.swing.JLabel jLabelPeaoYellow4;
    private javax.swing.JLabel jLabelTabuleiero;
    private javax.swing.JLabel jLabelUser1;
    private javax.swing.JLabel jLabelUser2;
    private javax.swing.JLabel jLabelUser3;
    private javax.swing.JLabel jLabelUser4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
