/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.PanelRankingControl;
import Model.RankingModel;
import Model.UserRanking;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paabl
 */
public class PanelRankingView extends javax.swing.JPanel {

    PanelRankingControl control;
    private JTable tabela;
    private DefaultTableModel modelo;
    
    /**
     * Creates new form Tabuleiro
     */
    
     public PanelRankingView() {
        control = new PanelRankingControl(this);
        criaJTable();
        initComponents();
        jScrollPane1.setViewportView(tabela);
        
        
        
        for(UserRanking u: RankingModel.getRanking() )    
             modelo.addRow(new Object[] {u.getLogin(),u.getQuantidadeVitorias(),u.getPartJogadas()});
        
    }

     private void criaJTable(){
        modelo = new DefaultTableModel();
        tabela = new JTable(modelo);
        modelo.addColumn("Login");
        modelo.addColumn("Partidas");
        modelo.addColumn("Vitórias");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jButtonSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);
        add(jScrollPane1);
        jScrollPane1.setBounds(100, 100, 580, 400);

        jButtonSair.setBackground(new java.awt.Color(255, 255, 204));
        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageViews/logoutDOOR.png"))); // NOI18N
        jButtonSair.setBorder(null);
        jButtonSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        add(jButtonSair);
        jButtonSair.setBounds(760, 10, 33, 33);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageViews/Winners.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(430, 0, 120, 100);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageViews/Ludo_logo2.png"))); // NOI18N
        add(jLabel6);
        jLabel6.setBounds(250, 0, 170, 90);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageViews/a-soft-sky-with-cloud-background-in-pastel-color-abstract-gradation-color-pastel_6529-11.jpg"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(0, 0, 630, 420);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageViews/a-soft-sky-with-cloud-background-in-pastel-color-abstract-gradation-color-pastel_6529-11.jpg"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(170, 0, 630, 420);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageViews/a-soft-sky-with-cloud-background-in-pastel-color-abstract-gradation-color-pastel_6529-11.jpg"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(170, 140, 630, 420);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageViews/a-soft-sky-with-cloud-background-in-pastel-color-abstract-gradation-color-pastel_6529-11.jpg"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(0, 140, 630, 420);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed

        int reply = JOptionPane.showConfirmDialog(null, "Tem certeza que você deseja sair", "Fazer logout", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            control.viewAnterior();
        }
    }//GEN-LAST:event_jButtonSairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
