/*
* To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.PanelTabuleiroControl;
import Model.CorPeça;
import static Model.CorPeça.AMARELO;
import static Model.CorPeça.AZUL;
import static Model.CorPeça.VERDE;
import static Model.CorPeça.VERMELHO;
import Model.Dado;
import Model.JogadorModel;
import Model.Peça;
import Util.DadoTimerTask;
import Util.MovimentaDado;
import java.awt.Point;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import songs.TocarSom;

/**
 *
 * @author paabl
 */
public class PanelTabuleiroView extends javax.swing.JPanel {
    private final Random randomGenerator;
    private final int MAX_ICONS = 6;
    private final ImageIcon[] framesDado = new ImageIcon[MAX_ICONS];
    MovimentaDado movimentDado;
    PanelTabuleiroControl control;
    private final String nomeAvatarJogador;
     JOptionPane msg = new JOptionPane("");
    final JDialog dlg = msg.createDialog("");

    
    public PanelTabuleiroView() {
        control = new PanelTabuleiroControl(this);
        initComponents();
        
        nomeAvatarJogador = JogadorModel.USER_LOGGED.getAvatar();
        Icon avatar = new javax.swing.ImageIcon(getClass().getResource("/ImageAvatars/"+nomeAvatarJogador));
        jLabelJogador.setIcon(avatar);
        
        
        randomGenerator = new Random();
        preencheVetorFramesDado();
        movimentDado = new MovimentaDado(jBtnDado1,framesDado);
        movimentDado.start(900);
        
        
        dlg.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        dlg.setLocation(-1000,-1000);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonVoltar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jBtnDado1 = new javax.swing.JButton();
        jLabelPeaoYellow2 = new javax.swing.JLabel();
        jLabelPeaoYellow1 = new javax.swing.JLabel();
        jLabelPeaoYellow3 = new javax.swing.JLabel();
        jLabelPeaoYellow4 = new javax.swing.JLabel();
        jLabelJogador = new javax.swing.JLabel();
        jLabelUser13 = new javax.swing.JLabel();
        jLabelUser14 = new javax.swing.JLabel();
        jLabelUser15 = new javax.swing.JLabel();
        jLabelPeaoBlue4 = new javax.swing.JLabel();
        jLabelPeaoBlue3 = new javax.swing.JLabel();
        jLabelPeaoBlue1 = new javax.swing.JLabel();
        jLabelPeaoBlue2 = new javax.swing.JLabel();
        jLabelPeaoRed3 = new javax.swing.JLabel();
        jLabelPeaoRed4 = new javax.swing.JLabel();
        jLabelPeaoGreen1 = new javax.swing.JLabel();
        jLabelPeaoRed1 = new javax.swing.JLabel();
        jLabelPeaoRed2 = new javax.swing.JLabel();
        jLabelPeaoGreen4 = new javax.swing.JLabel();
        jLabelPeaoGreen3 = new javax.swing.JLabel();
        jLabelPeaoGreen2 = new javax.swing.JLabel();
        jLabelTabuleiero3 = new javax.swing.JLabel();
        jLabelCircleYellow3 = new javax.swing.JLabel();
        jLabelCircleBlue3 = new javax.swing.JLabel();
        jLabelCircleGreen3 = new javax.swing.JLabel();
        jLabelCircleRed3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 253, 165));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 253, 165));

        jButtonVoltar.setBackground(new java.awt.Color(255, 253, 165));
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageViews/logoutDOOR.png"))); // NOI18N
        jButtonVoltar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(1233, Short.MAX_VALUE)
                .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel8.setBackground(new java.awt.Color(255, 253, 165));
        jPanel8.setLayout(null);

        jBtnDado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesDado/dado1.png"))); // NOI18N
        jBtnDado1.setBorder(null);
        jBtnDado1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnDado1.setName(""); // NOI18N
        jBtnDado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDado1ActionPerformed(evt);
            }
        });
        jPanel8.add(jBtnDado1);
        jBtnDado1.setBounds(290, 400, 40, 40);

        jLabelPeaoYellow2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-yellow.png"))); // NOI18N
        jLabelPeaoYellow2.setToolTipText("0");
        jLabelPeaoYellow2.setName("jLabelPeaoYellow2"); // NOI18N
        jLabelPeaoYellow2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPeaoMouseClicked(evt);
            }
        });
        jPanel8.add(jLabelPeaoYellow2);
        jLabelPeaoYellow2.setBounds(440, 570, 23, 32);

        jLabelPeaoYellow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-yellow.png"))); // NOI18N
        jLabelPeaoYellow1.setToolTipText("0");
        jLabelPeaoYellow1.setName("jLabelPeaoYellow1"); // NOI18N
        jLabelPeaoYellow1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPeaoMouseClicked(evt);
            }
        });
        jPanel8.add(jLabelPeaoYellow1);
        jLabelPeaoYellow1.setBounds(560, 590, 23, 32);

        jLabelPeaoYellow3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-yellow.png"))); // NOI18N
        jLabelPeaoYellow3.setToolTipText("0");
        jLabelPeaoYellow3.setName("jLabelPeaoYellow3"); // NOI18N
        jLabelPeaoYellow3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPeaoMouseClicked(evt);
            }
        });
        jPanel8.add(jLabelPeaoYellow3);
        jLabelPeaoYellow3.setBounds(410, 530, 23, 32);

        jLabelPeaoYellow4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-yellow.png"))); // NOI18N
        jLabelPeaoYellow4.setToolTipText("0");
        jLabelPeaoYellow4.setName("jLabelPeaoYellow4"); // NOI18N
        jLabelPeaoYellow4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPeaoMouseClicked(evt);
            }
        });
        jPanel8.add(jLabelPeaoYellow4);
        jLabelPeaoYellow4.setBounds(440, 500, 23, 32);

        jLabelJogador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAvatars/avatar5.png"))); // NOI18N
        jLabelJogador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jPanel8.add(jLabelJogador);
        jLabelJogador.setBounds(150, 430, 70, 80);

        jLabelUser13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAvatars/avatar5.png"))); // NOI18N
        jLabelUser13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jPanel8.add(jLabelUser13);
        jLabelUser13.setBounds(1030, 400, 70, 80);

        jLabelUser14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAvatars/avatar5.png"))); // NOI18N
        jLabelUser14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jPanel8.add(jLabelUser14);
        jLabelUser14.setBounds(1020, 30, 70, 80);

        jLabelUser15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAvatars/avatar5.png"))); // NOI18N
        jLabelUser15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jPanel8.add(jLabelUser15);
        jLabelUser15.setBounds(130, 40, 70, 70);

        jLabelPeaoBlue4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-blue.png"))); // NOI18N
        jLabelPeaoBlue4.setToolTipText("3");
        jLabelPeaoBlue4.setName("jLabelPeaoBlue4"); // NOI18N
        jPanel8.add(jLabelPeaoBlue4);
        jLabelPeaoBlue4.setBounds(820, 500, 23, 32);

        jLabelPeaoBlue3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-blue.png"))); // NOI18N
        jLabelPeaoBlue3.setToolTipText("2");
        jLabelPeaoBlue3.setName("jLabelPeaoBlue3"); // NOI18N
        jPanel8.add(jLabelPeaoBlue3);
        jLabelPeaoBlue3.setBounds(850, 470, 23, 32);

        jLabelPeaoBlue1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-blue.png"))); // NOI18N
        jLabelPeaoBlue1.setToolTipText("0");
        jLabelPeaoBlue1.setName("jLabelPeaoBlue1"); // NOI18N
        jPanel8.add(jLabelPeaoBlue1);
        jLabelPeaoBlue1.setBounds(870, 340, 23, 32);

        jLabelPeaoBlue2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-blue.png"))); // NOI18N
        jLabelPeaoBlue2.setToolTipText("1");
        jLabelPeaoBlue2.setName("jLabelPeaoBlue2"); // NOI18N
        jPanel8.add(jLabelPeaoBlue2);
        jLabelPeaoBlue2.setBounds(820, 430, 23, 32);

        jLabelPeaoRed3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-red-th4.png"))); // NOI18N
        jLabelPeaoRed3.setToolTipText("2");
        jLabelPeaoRed3.setName("jLabelPeaoRed3"); // NOI18N
        jPanel8.add(jLabelPeaoRed3);
        jLabelPeaoRed3.setBounds(790, 90, 23, 40);

        jLabelPeaoRed4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-red-th4.png"))); // NOI18N
        jLabelPeaoRed4.setToolTipText("3");
        jLabelPeaoRed4.setName("jLabelPeaoRed4"); // NOI18N
        jPanel8.add(jLabelPeaoRed4);
        jLabelPeaoRed4.setBounds(750, 120, 23, 40);

        jLabelPeaoGreen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-green.png"))); // NOI18N
        jLabelPeaoGreen1.setToolTipText("0");
        jLabelPeaoGreen1.setName("jLabelPeaoGreen1"); // NOI18N
        jPanel8.add(jLabelPeaoGreen1);
        jLabelPeaoGreen1.setBounds(320, 270, 30, 40);

        jLabelPeaoRed1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-red-th4.png"))); // NOI18N
        jLabelPeaoRed1.setToolTipText("0");
        jLabelPeaoRed1.setName("jLabelPeaoRed1"); // NOI18N
        jPanel8.add(jLabelPeaoRed1);
        jLabelPeaoRed1.setBounds(635, 25, 23, 40);

        jLabelPeaoRed2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-red-th4.png"))); // NOI18N
        jLabelPeaoRed2.setToolTipText("1");
        jLabelPeaoRed2.setName("jLabelPeaoRed2"); // NOI18N
        jPanel8.add(jLabelPeaoRed2);
        jLabelPeaoRed2.setBounds(750, 50, 23, 40);

        jLabelPeaoGreen4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-green.png"))); // NOI18N
        jLabelPeaoGreen4.setToolTipText("3");
        jLabelPeaoGreen4.setName("jLabelPeaoGreen4"); // NOI18N
        jPanel8.add(jLabelPeaoGreen4);
        jLabelPeaoGreen4.setBounds(370, 190, 30, 40);

        jLabelPeaoGreen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-green.png"))); // NOI18N
        jLabelPeaoGreen3.setToolTipText("2");
        jLabelPeaoGreen3.setName("jLabelPeaoGreen3"); // NOI18N
        jPanel8.add(jLabelPeaoGreen3);
        jLabelPeaoGreen3.setBounds(410, 150, 30, 40);

        jLabelPeaoGreen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-green.png"))); // NOI18N
        jLabelPeaoGreen2.setToolTipText("1");
        jLabelPeaoGreen2.setName("jLabelPeaoGreen2"); // NOI18N
        jPanel8.add(jLabelPeaoGreen2);
        jLabelPeaoGreen2.setBounds(370, 120, 30, 40);

        jLabelTabuleiero3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageViews/tabu.png"))); // NOI18N
        jLabelTabuleiero3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel8.add(jLabelTabuleiero3);
        jLabelTabuleiero3.setBounds(280, 10, 656, 653);

        jLabelCircleYellow3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageViews/yellow-circle-design-hi.png"))); // NOI18N
        jLabelCircleYellow3.setText("Dado 1");
        jPanel8.add(jLabelCircleYellow3);
        jLabelCircleYellow3.setBounds(10, 370, 300, 360);

        jLabelCircleBlue3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageViews/blue-circle-design-hi.png"))); // NOI18N
        jPanel8.add(jLabelCircleBlue3);
        jLabelCircleBlue3.setBounds(890, 380, 350, 345);

        jLabelCircleGreen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageViews/green-circle-design-hi.png"))); // NOI18N
        jPanel8.add(jLabelCircleGreen3);
        jLabelCircleGreen3.setBounds(10, 21, 350, 345);

        jLabelCircleRed3.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.activeTitleGradient"));
        jLabelCircleRed3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageViews/red-circle-design-hi.png"))); // NOI18N
        jPanel8.add(jLabelCircleRed3);
        jLabelCircleRed3.setBounds(870, 10, 360, 350);

        add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 253, 165));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 735, Short.MAX_VALUE)
        );

        add(jPanel2, java.awt.BorderLayout.EAST);

        jPanel3.setBackground(new java.awt.Color(255, 253, 165));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 735, Short.MAX_VALUE)
        );

        add(jPanel3, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents

    
    private void jBtnDado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDado1ActionPerformed
        if(Dado.getNum() == 6){
            //Button2.setVisible(true);
            if(!MovimentaDado.isRunning())
                movimentDado.start(900);
        }// TODO add your handling code here:

       // movimentDado.start(900);
    }//GEN-LAST:event_jBtnDado1ActionPerformed

    private void jLabelPeaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPeaoMouseClicked
         if (MovimentaDado.isRunning()){
             JOptionPane.showMessageDialog(this, "Espere o dado parar antes de mover a peça");
             return;
        }
        
        JLabel peaoClicado = (JLabel)evt.getSource();

        if(control.getCorDoJogadorDaVez() == AMARELO && peaoClicado.getName().contains("jLabelPeaoYellow")){
            movimentaPeao("Yellow",peaoClicado);
        }
    }//GEN-LAST:event_jLabelPeaoMouseClicked
       
    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
         int reply = JOptionPane.showConfirmDialog(null, "Tem certeza que você deseja sair", "Fazer logout", JOptionPane.YES_NO_OPTION);
         if (reply == JOptionPane.YES_OPTION) {
            
            JogadorModel.USER_LOGGED.setQtdPartidas( JogadorModel.USER_LOGGED.getQtdPartidas()+1);
            JogadorModel.updateUser();
            control.viewAnterior();
 
        }
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void movimentaPeao(String str, JLabel peaoClicado){
        
        if(peaoClicado.getName().contains("jLabelPeao"+str+"1")){
            control.getJogadorDaVez().escolhePeça(0);
        }
        else if(peaoClicado.getName().contains("jLabelPeao"+str+"2")){
            control.getJogadorDaVez().escolhePeça(1);
        }
        else if(peaoClicado.getName().contains("jLabelPeao"+str+"3")){
            control.getJogadorDaVez().escolhePeça(2);
        }
        else if(peaoClicado.getName().contains("jLabelPeao"+str+"4")){
            control.getJogadorDaVez().escolhePeça(3);
        }
        
        try{
            Point p = control.movimentaPeao();
            //peaoClicado.setLocation(p); 
            deslocaPeao(peaoClicado);
             sleep(500);
            atualizaView();
        }
        catch(java.lang.NullPointerException e){
            JOptionPane.showMessageDialog(this, "Você não pode mover a peça escolhida com o dado atual.", "", ERROR_MESSAGE);
             sleep(500);
            atualizaView();
        }
      
    }                                                                                      

    
    private void preencheVetorFramesDado() {
        for (int i = 1; i <= MAX_ICONS; i++) 
            framesDado[i-1] = new javax.swing.ImageIcon(getClass().getResource("/ImagesDado/dado"+i+".png"));
    }

    private void atualizaView() {
      
        
        if(control.proximoJogadorDaVez()){
            switch(control.getCorDoJogadorDaVez()){
            
            case AMARELO:   updatePositionDados(new Point(300,400)); 
                            sleep(1000);
                            movimentDado.start(900);
                            //MovimentaDado.stopTimerTask();
                            //movimentDado.start(900);
                            break;
            case VERDE:     updatePositionDados(new Point(290,20));
                            //control.getJogador(VERDE).
                            sleep(1000);
                            movimentDado.start(900);
                            movimentaPeao(VERDE);
                            break;
            case VERMELHO:  updatePositionDados(new Point(880,20)); 
                            sleep(1000);        
                            movimentDado.start(900);
                            movimentaPeao(VERMELHO);
                            break;
            case AZUL:      updatePositionDados(new Point(830,610));
                             sleep(1000);
                            movimentDado.start(900);
                            movimentaPeao(AZUL);
                            break;
            }   
        }
        else{
        
              JOptionPane.showMessageDialog(this,"O jogador "+control.getCorDoJogadorDaVez()+" venceu o jogo !!");
              
              if(control.getCorDoJogadorDaVez()== AMARELO){
                  JogadorModel.USER_LOGGED.setQtdVitorias(JogadorModel.USER_LOGGED.getQtdVitorias()+1);
                  JogadorModel.updateUser();   
              }
        } 
    }

    private void updatePositionDados(Point PosBtn1) {
         jBtnDado1.setLocation(PosBtn1);
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnDado1;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabelCircleBlue3;
    private javax.swing.JLabel jLabelCircleGreen3;
    private javax.swing.JLabel jLabelCircleRed3;
    private javax.swing.JLabel jLabelCircleYellow3;
    private javax.swing.JLabel jLabelJogador;
    private javax.swing.JLabel jLabelPeaoBlue1;
    private javax.swing.JLabel jLabelPeaoBlue2;
    private javax.swing.JLabel jLabelPeaoBlue3;
    private javax.swing.JLabel jLabelPeaoBlue4;
    private javax.swing.JLabel jLabelPeaoGreen1;
    private javax.swing.JLabel jLabelPeaoGreen2;
    private javax.swing.JLabel jLabelPeaoGreen3;
    private javax.swing.JLabel jLabelPeaoGreen4;
    private javax.swing.JLabel jLabelPeaoRed1;
    private javax.swing.JLabel jLabelPeaoRed2;
    private javax.swing.JLabel jLabelPeaoRed3;
    private javax.swing.JLabel jLabelPeaoRed4;
    private javax.swing.JLabel jLabelPeaoYellow1;
    private javax.swing.JLabel jLabelPeaoYellow2;
    private javax.swing.JLabel jLabelPeaoYellow3;
    private javax.swing.JLabel jLabelPeaoYellow4;
    private javax.swing.JLabel jLabelTabuleiero3;
    private javax.swing.JLabel jLabelUser13;
    private javax.swing.JLabel jLabelUser14;
    private javax.swing.JLabel jLabelUser15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables

 
    
    private void movimentaPeao(CorPeça corDoJogadorDaVez) {
        
        sleep(1100);
        
        MovimentaDado.stopTimerTask();
        Point p = control.movimentaPeao();
        
        try{
            int i;
        if(corDoJogadorDaVez == VERDE){
            i = control.getJogador(VERDE).getIndexPeçaAtualEscolhida();
            switch(i){
                case 0: deslocaPeao(jLabelPeaoGreen1);break;
                case 1: deslocaPeao(jLabelPeaoGreen2);break;
                case 2: deslocaPeao(jLabelPeaoGreen3);break;
                case 3: deslocaPeao(jLabelPeaoGreen4);break;
            }
        }
        
        else if(corDoJogadorDaVez == VERMELHO){
            i = control.getJogador(VERMELHO).getIndexPeçaAtualEscolhida();
            switch(i){
                case 0: deslocaPeao(jLabelPeaoRed1);break;
                case 1: deslocaPeao(jLabelPeaoRed2);break;
                case 2: deslocaPeao(jLabelPeaoRed3);break;
                case 3: deslocaPeao(jLabelPeaoRed4);break;
            
            }
        }
        
        else{
            i = control.getJogador(AZUL).getIndexPeçaAtualEscolhida();
            switch(i){
                case 0: deslocaPeao(jLabelPeaoBlue1);break;
                case 1: deslocaPeao(jLabelPeaoBlue2);break;
                case 2: deslocaPeao(jLabelPeaoBlue3);break;
                case 3: deslocaPeao(jLabelPeaoBlue4);break;
            }
        }
        sleep(500);
        atualizaView();
    }
    catch(java.lang.NullPointerException e){
         sleep(500);
        atualizaView();
    }
    }

    private void deslocaPeao(JLabel jLabelPeao) {
        Peça pe = control.getJogadorDaVez().getPeçaEscolhida();
        Point p = null;
        
        for(int i = pe.getCasaIndexAntiga(); i <= pe.getIndexCasaAtual() ; i++){
              try {
            TocarSom t = new TocarSom();
            t.tocaSom("movendo_pino.wav");
        } catch (IOException ex) {
            Logger.getLogger(DadoTimerTask.class.getName()).log(Level.SEVERE, null, ex);
        }
            p = pe.getPoint(i);
            jLabelPeao.setLocation(p);
            sleep(200);
            
           // System.out.print(Tabuleiro.contains(p));
        }
        
         JLabel peao = getPeaoMesmaPosicao(jLabelPeao,pe.getCor());
         Peça peça;
         if(peao != null){
             if(peao.getName().contains("Yellow")){
                 if(peao.getName().contains("1")){
                     peça = control.getJogador(AMARELO).getPeça(0);
                 }
                 else if(peao.getName().contains("2")){
                     peça = control.getJogador(AMARELO).getPeça(1);
                 }
                 else if(peao.getName().contains("3")){
                     peça = control.getJogador(AMARELO).getPeça(2);
                 }
                 else{
                     peça = control.getJogador(AMARELO).getPeça(3);
                 }
             }
             else if(peao.getName().contains("Red")){
                 if(peao.getName().contains("1")){
                     peça = control.getJogador(VERMELHO).getPeça(0);
                 }
                 else if(peao.getName().contains("2")){
                     peça = control.getJogador(VERMELHO).getPeça(1);
                 }
                 else if(peao.getName().contains("3")){
                     peça = control.getJogador(VERMELHO).getPeça(2);
                 }
                 else{
                     peça = control.getJogador(VERMELHO).getPeça(3);
                 }
             }
             else if(peao.getName().contains("Blue")){
                 if(peao.getName().contains("1")){
                     peça = control.getJogador(AZUL).getPeça(0);
                 }
                 else if(peao.getName().contains("2")){
                     peça = control.getJogador(AZUL).getPeça(1);
                 }
                 else if(peao.getName().contains("3")){
                     peça = control.getJogador(AZUL).getPeça(2);
                 }
                 else{
                     peça = control.getJogador(AZUL).getPeça(3);
                 }
             }
             else{
                 if(peao.getName().contains("1")){
                     peça = control.getJogador(VERDE).getPeça(0);
                 }
                 else if(peao.getName().contains("2")){
                     peça = control.getJogador(VERDE).getPeça(1);
                 }
                 else if(peao.getName().contains("3")){
                     peça = control.getJogador(VERDE).getPeça(2);
                 }
                 else{
                     peça = control.getJogador(VERDE).getPeça(3);
                 }
             }
             peao.setLocation(peça.getLocationBase());
             peça.setNaBase(true);
         }
            
    }
    
    private void sleep(int n) {
        new Thread(new Runnable() {
          @Override
          public void run() {
            try {
              Thread.sleep(n);
            } catch (InterruptedException e) {
              e.printStackTrace();
            }
            dlg.setVisible(false);
          }
        }).start();
        dlg.setVisible(true);
    }

    private JLabel getPeaoMesmaPosicao(JLabel jLabelPeao,CorPeça cor) {
        
        JLabel peao = null;
        
        switch(cor){
            case AMARELO:  peao = verificaPeao(AMARELO,jLabelPeao); break;
            case VERMELHO:  peao = verificaPeao(VERMELHO,jLabelPeao); break;
            case AZUL:  peao = verificaPeao(AZUL,jLabelPeao); break;
            case VERDE:  peao = verificaPeao(VERDE,jLabelPeao); break;
        }
        return peao;
    }

    private JLabel verificaPeao(CorPeça cor, JLabel jLabelPeao) {
       
        JLabel peao = null;

        if(cor == AMARELO){
            //compara com verde
            if(jLabelPeao.getLocation().equals(jLabelPeaoGreen1.getLocation()))
                peao = jLabelPeaoGreen1;
            else if(jLabelPeao.getLocation().equals(jLabelPeaoGreen2.getLocation()))
                peao = jLabelPeaoGreen2;
            else if(jLabelPeao.getLocation().equals(jLabelPeaoGreen3.getLocation()))
                peao = jLabelPeaoGreen3;    
            else if(jLabelPeao.getLocation().equals(jLabelPeaoGreen4.getLocation()))
                peao = jLabelPeaoGreen4;
            
            //Compara com vermelehos
            else if(jLabelPeao.getLocation().equals(jLabelPeaoRed1.getLocation()))
                peao = jLabelPeaoRed1;
            else if(jLabelPeao.getLocation().equals(jLabelPeaoRed2.getLocation()))
                peao = jLabelPeaoRed2;
            else if(jLabelPeao.getLocation().equals(jLabelPeaoRed3.getLocation()))
                peao = jLabelPeaoRed3;    
            else if(jLabelPeao.getLocation().equals(jLabelPeaoRed4.getLocation()))
                peao = jLabelPeaoRed4;   
                
            //compara com azul
            else if(jLabelPeao.getLocation().equals(jLabelPeaoBlue1.getLocation()))
                peao = jLabelPeaoBlue1;
            else if(jLabelPeao.getLocation().equals(jLabelPeaoBlue2.getLocation()))
                peao = jLabelPeaoBlue2;
            else if(jLabelPeao.getLocation().equals(jLabelPeaoBlue3.getLocation()))
                peao = jLabelPeaoBlue3;    
            else if(jLabelPeao.getLocation().equals(jLabelPeaoBlue4.getLocation()))
                peao = jLabelPeaoBlue4;   
        }
        else if(cor == VERMELHO){
             //compara com amarelo
            if(jLabelPeao.getLocation().equals(jLabelPeaoYellow1.getLocation()))
                peao = jLabelPeaoYellow1;
            else if(jLabelPeao.getLocation().equals(jLabelPeaoYellow2.getLocation()))
                peao = jLabelPeaoYellow2;
            else if(jLabelPeao.getLocation().equals(jLabelPeaoYellow3.getLocation()))
                peao = jLabelPeaoYellow3;    
            else if(jLabelPeao.getLocation().equals(jLabelPeaoYellow4.getLocation()))
                peao = jLabelPeaoYellow4;
        
            //compara com verde
            else if(jLabelPeao.getLocation().equals(jLabelPeaoGreen1.getLocation()))
                peao = jLabelPeaoGreen1;
            else if(jLabelPeao.getLocation().equals(jLabelPeaoGreen2.getLocation()))
                peao = jLabelPeaoGreen2;
            else if(jLabelPeao.getLocation().equals(jLabelPeaoGreen3.getLocation()))
                peao = jLabelPeaoGreen3;    
            else if(jLabelPeao.getLocation().equals(jLabelPeaoGreen4.getLocation()))
                peao = jLabelPeaoGreen4;
            
             //compara com azul
            else if(jLabelPeao.getLocation().equals(jLabelPeaoBlue1.getLocation()))
                peao = jLabelPeaoBlue1;
            else if(jLabelPeao.getLocation().equals(jLabelPeaoBlue2.getLocation()))
                peao = jLabelPeaoBlue2;
            else if(jLabelPeao.getLocation().equals(jLabelPeaoBlue3.getLocation()))
                peao = jLabelPeaoBlue3;    
            else if(jLabelPeao.getLocation().equals(jLabelPeaoBlue4.getLocation()))
                peao = jLabelPeaoBlue4;   
        
        }
        
         else if(cor == VERDE){
              //compara com amarelo
            if(jLabelPeao.getLocation().equals(jLabelPeaoYellow1.getLocation()))
                peao = jLabelPeaoYellow1;
            else if(jLabelPeao.getLocation().equals(jLabelPeaoYellow2.getLocation()))
                peao = jLabelPeaoYellow2;
            else if(jLabelPeao.getLocation().equals(jLabelPeaoYellow3.getLocation()))
                peao = jLabelPeaoYellow3;    
            else if(jLabelPeao.getLocation().equals(jLabelPeaoYellow4.getLocation()))
                peao = jLabelPeaoYellow4;
            
             //compara com azul
            else if(jLabelPeao.getLocation().equals(jLabelPeaoBlue1.getLocation()))
                peao = jLabelPeaoBlue1;
            else if(jLabelPeao.getLocation().equals(jLabelPeaoBlue2.getLocation()))
                peao = jLabelPeaoBlue2;
            else if(jLabelPeao.getLocation().equals(jLabelPeaoBlue3.getLocation()))
                peao = jLabelPeaoBlue3;    
            else if(jLabelPeao.getLocation().equals(jLabelPeaoBlue4.getLocation()))
                peao = jLabelPeaoBlue4;  
         
             //Compara com vermelehos
            else if(jLabelPeao.getLocation().equals(jLabelPeaoRed1.getLocation()))
                peao = jLabelPeaoRed1;
            else if(jLabelPeao.getLocation().equals(jLabelPeaoRed2.getLocation()))
                peao = jLabelPeaoRed2;
            else if(jLabelPeao.getLocation().equals(jLabelPeaoRed3.getLocation()))
                peao = jLabelPeaoRed3;    
            else if(jLabelPeao.getLocation().equals(jLabelPeaoRed4.getLocation()))
                peao = jLabelPeaoRed4; 
         }
        
         else if(cor == AZUL){
                //compara com amarelo
            if(jLabelPeao.getLocation().equals(jLabelPeaoYellow1.getLocation()))
                peao = jLabelPeaoYellow1;
            else if(jLabelPeao.getLocation().equals(jLabelPeaoYellow2.getLocation()))
                peao = jLabelPeaoYellow2;
            else if(jLabelPeao.getLocation().equals(jLabelPeaoYellow3.getLocation()))
                peao = jLabelPeaoYellow3;    
            else if(jLabelPeao.getLocation().equals(jLabelPeaoYellow4.getLocation()))
                peao = jLabelPeaoYellow4;
            
             //Compara com vermelhos
            else if(jLabelPeao.getLocation().equals(jLabelPeaoRed1.getLocation()))
                peao = jLabelPeaoRed1;
            else if(jLabelPeao.getLocation().equals(jLabelPeaoRed2.getLocation()))
                peao = jLabelPeaoRed2;
            else if(jLabelPeao.getLocation().equals(jLabelPeaoRed3.getLocation()))
                peao = jLabelPeaoRed3;    
            else if(jLabelPeao.getLocation().equals(jLabelPeaoRed4.getLocation()))
                peao = jLabelPeaoRed4; 
         
          //compara com verde
            else if(jLabelPeao.getLocation().equals(jLabelPeaoGreen1.getLocation()))
                peao = jLabelPeaoGreen1;
            else if(jLabelPeao.getLocation().equals(jLabelPeaoGreen2.getLocation()))
                peao = jLabelPeaoGreen2;
            else if(jLabelPeao.getLocation().equals(jLabelPeaoGreen3.getLocation()))
                peao = jLabelPeaoGreen3;    
            else if(jLabelPeao.getLocation().equals(jLabelPeaoGreen4.getLocation()))
                peao = jLabelPeaoGreen4;
            
         }
         return peao;
    }
}       
       
    

