/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Control.PanelMenuControl;
import Model.JogadorModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Lufh
 */
public class PanelMenuView extends javax.swing.JPanel {

    PanelMenuControl control;
    private String nomeAvatarJogador;
   
    
    /**
     * Creates new form Tabuleiro
     */
    
     public PanelMenuView() {
        initComponents();
        
        
        control = new PanelMenuControl(this);
        nomeAvatarJogador = JogadorModel.USER_LOGGED.getAvatar();
        Icon avatar = new javax.swing.ImageIcon(getClass().getResource("/ImageAvatars/"+nomeAvatarJogador));
        jLabelAvatarJogador.setIcon(avatar);
        jLabelLogin.setText("Login: "+JogadorModel.USER_LOGGED.getName());

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelAvatarJogador = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();
        btnJogar = new javax.swing.JButton();
        btnRanking = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jPanel1.setLayout(null);

        jLabelAvatarJogador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAvatars/avatar5.png"))); // NOI18N
        jLabelAvatarJogador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jPanel1.add(jLabelAvatarJogador);
        jLabelAvatarJogador.setBounds(80, 10, 70, 70);

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel7.setText("Ranking:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 140, 80, 20);

        jLabelLogin.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabelLogin.setText("Login:");
        jPanel1.add(jLabelLogin);
        jLabelLogin.setBounds(10, 110, 220, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageViews/back.png"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 0), 2, true));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 220, 170);

        add(jPanel1);
        jPanel1.setBounds(500, 90, 220, 170);

        jButtonSair.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageViews/logoutDOOR.png"))); // NOI18N
        jButtonSair.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        add(jButtonSair);
        jButtonSair.setBounds(760, 10, 35, 35);

        btnJogar.setBackground(new java.awt.Color(204, 204, 0));
        btnJogar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnJogar.setForeground(new java.awt.Color(255, 255, 255));
        btnJogar.setText("Jogar");
        btnJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogarActionPerformed(evt);
            }
        });
        add(btnJogar);
        btnJogar.setBounds(150, 360, 280, 40);

        btnRanking.setBackground(new java.awt.Color(0, 51, 255));
        btnRanking.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnRanking.setForeground(new java.awt.Color(255, 255, 255));
        btnRanking.setText("Ranking");
        btnRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRankingActionPerformed(evt);
            }
        });
        add(btnRanking);
        btnRanking.setBounds(150, 410, 280, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageViews/Ludo_logo.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(0, -10, 500, 300);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageViews/ludo2.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(500, 270, 300, 281);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageViews/a-soft-sky-with-cloud-background-in-pastel-color-abstract-gradation-color-pastel_6529-11.jpg"))); // NOI18N
        add(jLabelBackground);
        jLabelBackground.setBounds(100, 70, 626, 417);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed

        int reply = JOptionPane.showConfirmDialog(null, "Tem certeza que você deseja sair", "Fazer logout", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            control.viewAnterior();
        }

    }//GEN-LAST:event_jButtonSairActionPerformed

    private void btnRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRankingActionPerformed
        //control.ranking();
    }//GEN-LAST:event_btnRankingActionPerformed

    private void btnJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogarActionPerformed
        control.jogar();
    }//GEN-LAST:event_btnJogarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJogar;
    private javax.swing.JButton btnRanking;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelAvatarJogador;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

  
}
