/*
* To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.PanelTabuleiroControl;
import static Control.PanelTabuleiroControl.corDoJogadorDaVez.AMARELO;
import static Control.PanelTabuleiroControl.corDoJogadorDaVez.AZUL;
import static Control.PanelTabuleiroControl.corDoJogadorDaVez.VERDE;
import static Control.PanelTabuleiroControl.corDoJogadorDaVez.VERMELHO;
import Model.Peça;
import Model.PeçaAmarela;
import Model.PeçaAzul;
import Model.PeçaVerde;
import Model.PeçaVermelha;
import Model.Tabuleiro;
import Util.EnumDado;
import Util.MovimentaDado;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;


/**
 *
 * @author paabl
 */
public class PanelTabuleiroView extends javax.swing.JPanel {

    private Timer timerAnimateDado2;
    private Timer timerAnimateDado1;
    private final int MAX_ICONS = 6;
    private final ImageIcon[] framesDado = new ImageIcon[MAX_ICONS];
    MovimentaDado movimentaDado;
    PanelTabuleiroControl control;
    
    public PanelTabuleiroView() {
        control = new PanelTabuleiroControl(this);
        initComponents();
        
        preencheVetorFramesDado();
        
       // createListenersAnimeDados();
        createListenersLayoutDado();
 
        inicToolTipPeoes();
        
        movimentaDado = new MovimentaDado(jBtnDado1,jBtnDado2,framesDado);
        //movimentaDado.start(5000, EnumDado.Primeiro);
        
       // timerAnimateDado1.start();
        //timerAnimateDado2.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonVoltar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabelVermelho = new javax.swing.JLabel();
        jLabelAzul = new javax.swing.JLabel();
        jLabelAmarelo = new javax.swing.JLabel();
        jLabelVerde = new javax.swing.JLabel();
        jBtnDado1 = new javax.swing.JToggleButton();
        jBtnDado2 = new javax.swing.JToggleButton();
        jLabelUser9 = new javax.swing.JLabel();
        jLabelUser10 = new javax.swing.JLabel();
        jLabelUser11 = new javax.swing.JLabel();
        jLabelUser12 = new javax.swing.JLabel();
        jLabelPeaoYellow1 = new javax.swing.JLabel();
        jLabelPeaoBlue4 = new javax.swing.JLabel();
        jLabelPeaoBlue3 = new javax.swing.JLabel();
        jLabelPeaoBlue1 = new javax.swing.JLabel();
        jLabelPeaoYellow2 = new javax.swing.JLabel();
        jLabelPeaoBlue2 = new javax.swing.JLabel();
        jLabelPeaoYellow3 = new javax.swing.JLabel();
        jLabelPeaoYellow4 = new javax.swing.JLabel();
        jLabelPeaoRed3 = new javax.swing.JLabel();
        jLabelPeaoRed4 = new javax.swing.JLabel();
        jLabelPeaoGreen1 = new javax.swing.JLabel();
        jLabelPeaoRed1 = new javax.swing.JLabel();
        jLabelPeaoRed2 = new javax.swing.JLabel();
        jLabelPeaoGreen4 = new javax.swing.JLabel();
        jLabelPeaoGreen3 = new javax.swing.JLabel();
        jLabelPeaoGreen2 = new javax.swing.JLabel();
        jLabelTabuleiero2 = new javax.swing.JLabel();
        jLabelCircleYellow2 = new javax.swing.JLabel();
        jLabelCircleBlue2 = new javax.swing.JLabel();
        jLabelCircleGreen2 = new javax.swing.JLabel();
        jLabelCircleRed2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 253, 165));

        jButtonVoltar.setBackground(new java.awt.Color(255, 253, 165));
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageViews/logoutDOOR.png"))); // NOI18N
        jButtonVoltar.setBorder(null);
        jButtonVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 253, 165));
        jPanel7.setLayout(null);

        jLabelVermelho.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelVermelho.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jLabelVermelho);
        jLabelVermelho.setBounds(940, 180, 220, 50);

        jLabelAzul.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelAzul.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jLabelAzul);
        jLabelAzul.setBounds(940, 530, 220, 50);

        jLabelAmarelo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelAmarelo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jLabelAmarelo);
        jLabelAmarelo.setBounds(50, 520, 220, 50);

        jLabelVerde.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelVerde.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jLabelVerde);
        jLabelVerde.setBounds(30, 170, 220, 50);

        jBtnDado1.setBackground(new java.awt.Color(255, 255, 255));
        jBtnDado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesDado/dado3.png"))); // NOI18N
        jBtnDado1.setBorder(null);
        jBtnDado1.setContentAreaFilled(false);
        jBtnDado1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnDado1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnDado1MouseClicked(evt);
            }
        });
        jPanel7.add(jBtnDado1);
        jBtnDado1.setBounds(290, 400, 40, 41);

        jBtnDado2.setBackground(new java.awt.Color(255, 255, 255));
        jBtnDado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesDado/dado3.png"))); // NOI18N
        jBtnDado2.setBorder(null);
        jBtnDado2.setContentAreaFilled(false);
        jBtnDado2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnDado2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnDado2MouseClicked(evt);
            }
        });
        jPanel7.add(jBtnDado2);
        jBtnDado2.setBounds(350, 400, 40, 41);

        jLabelUser9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAvatars/avatar2.png"))); // NOI18N
        jLabelUser9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jPanel7.add(jLabelUser9);
        jLabelUser9.setBounds(140, 390, 70, 80);

        jLabelUser10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAvatars/avatar4.png"))); // NOI18N
        jLabelUser10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jPanel7.add(jLabelUser10);
        jLabelUser10.setBounds(1030, 400, 70, 80);

        jLabelUser11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAvatars/avatar3.png"))); // NOI18N
        jLabelUser11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jPanel7.add(jLabelUser11);
        jLabelUser11.setBounds(1020, 30, 70, 80);

        jLabelUser12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageAvatars/avatar1.png"))); // NOI18N
        jLabelUser12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jPanel7.add(jLabelUser12);
        jLabelUser12.setBounds(130, 40, 70, 70);

        jLabelPeaoYellow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-yellow.png"))); // NOI18N
        jLabelPeaoYellow1.setName("jLabelPeaoYellow1"); // NOI18N
        jLabelPeaoYellow1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPeaoMouseClicked(evt);
            }
        });
        jPanel7.add(jLabelPeaoYellow1);
        jLabelPeaoYellow1.setBounds(560, 580, 23, 32);

        jLabelPeaoBlue4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-blue.png"))); // NOI18N
        jLabelPeaoBlue4.setName("jLabelPeaoBlue4"); // NOI18N
        jLabelPeaoBlue4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPeaoMouseClicked(evt);
            }
        });
        jPanel7.add(jLabelPeaoBlue4);
        jLabelPeaoBlue4.setBounds(820, 500, 23, 32);

        jLabelPeaoBlue3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-blue.png"))); // NOI18N
        jLabelPeaoBlue3.setName("jLabelPeaoBlue3"); // NOI18N
        jLabelPeaoBlue3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPeaoMouseClicked(evt);
            }
        });
        jPanel7.add(jLabelPeaoBlue3);
        jLabelPeaoBlue3.setBounds(850, 470, 23, 32);

        jLabelPeaoBlue1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-blue.png"))); // NOI18N
        jLabelPeaoBlue1.setName("jLabelPeaoBlue1"); // NOI18N
        jLabelPeaoBlue1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPeaoMouseClicked(evt);
            }
        });
        jPanel7.add(jLabelPeaoBlue1);
        jLabelPeaoBlue1.setBounds(870, 340, 23, 32);

        jLabelPeaoYellow2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-yellow.png"))); // NOI18N
        jLabelPeaoYellow2.setName("jLabelPeaoYellow2"); // NOI18N
        jLabelPeaoYellow2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPeaoMouseClicked(evt);
            }
        });
        jPanel7.add(jLabelPeaoYellow2);
        jLabelPeaoYellow2.setBounds(440, 570, 23, 32);

        jLabelPeaoBlue2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-blue.png"))); // NOI18N
        jLabelPeaoBlue2.setName("jLabelPeaoBlue2"); // NOI18N
        jLabelPeaoBlue2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPeaoMouseClicked(evt);
            }
        });
        jPanel7.add(jLabelPeaoBlue2);
        jLabelPeaoBlue2.setBounds(820, 430, 23, 32);

        jLabelPeaoYellow3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-yellow.png"))); // NOI18N
        jLabelPeaoYellow3.setName("jLabelPeaoYellow3"); // NOI18N
        jLabelPeaoYellow3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPeaoMouseClicked(evt);
            }
        });
        jPanel7.add(jLabelPeaoYellow3);
        jLabelPeaoYellow3.setBounds(410, 530, 23, 32);

        jLabelPeaoYellow4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-yellow.png"))); // NOI18N
        jLabelPeaoYellow4.setName("jLabelPeaoYellow4"); // NOI18N
        jLabelPeaoYellow4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPeaoMouseClicked(evt);
            }
        });
        jPanel7.add(jLabelPeaoYellow4);
        jLabelPeaoYellow4.setBounds(440, 500, 23, 32);

        jLabelPeaoRed3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-red-th4.png"))); // NOI18N
        jLabelPeaoRed3.setName("jLabelPeaoRed3"); // NOI18N
        jLabelPeaoRed3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPeaoMouseClicked(evt);
            }
        });
        jPanel7.add(jLabelPeaoRed3);
        jLabelPeaoRed3.setBounds(790, 90, 23, 40);

        jLabelPeaoRed4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-red-th4.png"))); // NOI18N
        jLabelPeaoRed4.setName("jLabelPeaoRed4"); // NOI18N
        jLabelPeaoRed4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPeaoMouseClicked(evt);
            }
        });
        jPanel7.add(jLabelPeaoRed4);
        jLabelPeaoRed4.setBounds(750, 120, 23, 40);

        jLabelPeaoGreen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-green.png"))); // NOI18N
        jLabelPeaoGreen1.setName("jLabelPeaoGreen1"); // NOI18N
        jLabelPeaoGreen1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPeaoMouseClicked(evt);
            }
        });
        jPanel7.add(jLabelPeaoGreen1);
        jLabelPeaoGreen1.setBounds(320, 270, 30, 40);

        jLabelPeaoRed1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-red-th4.png"))); // NOI18N
        jLabelPeaoRed1.setName("jLabelPeaoRed1"); // NOI18N
        jLabelPeaoRed1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPeaoMouseClicked(evt);
            }
        });
        jPanel7.add(jLabelPeaoRed1);
        jLabelPeaoRed1.setBounds(635, 25, 23, 40);

        jLabelPeaoRed2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-red-th4.png"))); // NOI18N
        jLabelPeaoRed2.setName("jLabelPeaoRed2"); // NOI18N
        jLabelPeaoRed2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPeaoMouseClicked(evt);
            }
        });
        jPanel7.add(jLabelPeaoRed2);
        jLabelPeaoRed2.setBounds(750, 50, 23, 40);

        jLabelPeaoGreen4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-green.png"))); // NOI18N
        jLabelPeaoGreen4.setName("jLabelPeaoGreen4"); // NOI18N
        jLabelPeaoGreen4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPeaoMouseClicked(evt);
            }
        });
        jPanel7.add(jLabelPeaoGreen4);
        jLabelPeaoGreen4.setBounds(370, 190, 30, 40);

        jLabelPeaoGreen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-green.png"))); // NOI18N
        jLabelPeaoGreen3.setName("jLabelPeaoGreen3"); // NOI18N
        jLabelPeaoGreen3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPeaoMouseClicked(evt);
            }
        });
        jPanel7.add(jLabelPeaoGreen3);
        jLabelPeaoGreen3.setBounds(410, 150, 30, 40);

        jLabelPeaoGreen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-green.png"))); // NOI18N
        jLabelPeaoGreen2.setName("jLabelPeaoGreen2"); // NOI18N
        jLabelPeaoGreen2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPeaoMouseClicked(evt);
            }
        });
        jPanel7.add(jLabelPeaoGreen2);
        jLabelPeaoGreen2.setBounds(370, 120, 30, 40);

        jLabelTabuleiero2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageViews/tabu.png"))); // NOI18N
        jLabelTabuleiero2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel7.add(jLabelTabuleiero2);
        jLabelTabuleiero2.setBounds(280, 10, 656, 653);

        jLabelCircleYellow2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageViews/yellow-circle-design-hi.png"))); // NOI18N
        jLabelCircleYellow2.setText("Dado 1");
        jPanel7.add(jLabelCircleYellow2);
        jLabelCircleYellow2.setBounds(10, 380, 388, 345);

        jLabelCircleBlue2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageViews/blue-circle-design-hi.png"))); // NOI18N
        jPanel7.add(jLabelCircleBlue2);
        jLabelCircleBlue2.setBounds(890, 380, 350, 345);

        jLabelCircleGreen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageViews/green-circle-design-hi.png"))); // NOI18N
        jPanel7.add(jLabelCircleGreen2);
        jLabelCircleGreen2.setBounds(10, 21, 350, 345);

        jLabelCircleRed2.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.activeTitleGradient"));
        jLabelCircleRed2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageViews/red-circle-design-hi.png"))); // NOI18N
        jPanel7.add(jLabelCircleRed2);
        jLabelCircleRed2.setBounds(870, 20, 350, 345);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1197, 1197, 1197)
                .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(785, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(30, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
         int reply = JOptionPane.showConfirmDialog(null, "Tem certeza que você deseja sair", "Fazer logout", JOptionPane.YES_NO_OPTION);
         if (reply == JOptionPane.YES_OPTION) {
            control.viewAnterior();
        }
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jBtnDado2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDado2MouseClicked
       if (SwingUtilities.isRightMouseButton(evt)) {
           if(movimentaDado.isRunning(EnumDado.Segundo)){
               movimentaDado.stop(EnumDado.Segundo);
               control.lancarDado(EnumDado.Segundo);
               int valorDado2 = Tabuleiro.getNumDadoDois();
               jBtnDado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesDado/dado"+valorDado2+".png")));
           }
                
           else{
               movimentaDado.start(EnumDado.Segundo);
           }
       }
    }//GEN-LAST:event_jBtnDado2MouseClicked

    private void jBtnDado1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDado1MouseClicked
       if (SwingUtilities.isRightMouseButton(evt)) {
           if(movimentaDado.isRunning(EnumDado.Primeiro)){
               movimentaDado.stop(EnumDado.Primeiro);
               control.lancarDado(EnumDado.Primeiro);
               int valorDado1 = Tabuleiro.getNumDadoUm();
               jBtnDado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesDado/dado"+valorDado1+".png")));
           }
                
           else{
               movimentaDado.start(EnumDado.Primeiro);
           }
       }
    }//GEN-LAST:event_jBtnDado1MouseClicked

    private void jLabelPeaoMouseClicked(java.awt.event.MouseEvent evt) {                                        
       
        if (movimentaDado.isRunning(EnumDado.Ambos)){
             JOptionPane.showMessageDialog(this, "Pare todos os dados antes de mover a peça");
             return;
        }
        
        if(control.getCorDoJogadorDaVez() == AMARELO){
            JLabel peaoClicado = (JLabel)evt.getSource();
            Peça peçaEscolhida = null;
            
            if(peaoClicado.getName().contains("jLabelPeaoYellow1")){
                peçaEscolhida = control.getJogadorDaVez().getPeça(0);
            }
            else if(peaoClicado.getName().contains("jLabelPeaoYellow2")){
                peçaEscolhida = control.getJogadorDaVez().getPeça(1);
            }
            else if(peaoClicado.getName().contains("jLabelPeaoYellow3")){
             peçaEscolhida = control.getJogadorDaVez().getPeça(2);
            }
            else if(peaoClicado.getName().contains("jLabelPeaoYellow4")){
                peçaEscolhida = control.getJogadorDaVez().getPeça(3);
            }
            
            //try{
                movimentaPeça(peaoClicado,peçaEscolhida,qtdCasasParaAndar());
            //}
            //catch(Exception e){
              //  System.out.print(e.getMessage());
            //}
            
            
            
        }
    } 

     private void createListenersLayoutDado() {
        ActionListener startStopDado1;
        ActionListener startStopDado2;
       
        startStopDado1 = (ActionEvent e) -> {
            if (jBtnDado1.isSelected() ) {
                changeButtonLayout(jBtnDado1,true);
            } 
            else {
                changeButtonLayout(jBtnDado1,false);
            }
        };
        
        startStopDado2 = (ActionEvent e) -> {
            if (jBtnDado2.isSelected()) {
                changeButtonLayout(jBtnDado2,true);
            } 
            else {
                changeButtonLayout(jBtnDado2,false);
            }
        };

         jBtnDado1.addActionListener(startStopDado1);
         jBtnDado2.addActionListener(startStopDado2);
    }

    public void changeButtonLayout(JToggleButton jButton,boolean Border){
        Border preta = new LineBorder(Color.BLACK,2,true);
        Border branca = new LineBorder(Color.BLACK,0,true);
        
        if(Border){
            jButton.setBorder(preta);
            jButton.setSelected(true);
        }
            
        else{
            jButton.setBorder(branca);
            jButton.setSelected(false);
        }
            
            
    }
     
     
    //gambiarra
    private void inicToolTipPeoes() {
       jLabelPeaoGreen1.setToolTipText(""+0);
       jLabelPeaoRed1.setToolTipText(""+0);
       jLabelPeaoBlue1.setToolTipText(""+0);
       jLabelPeaoYellow1.setToolTipText(""+0);
    }
    
    private void preencheVetorFramesDado() {
        for (int i = 1; i <= MAX_ICONS; i++) 
            framesDado[i-1] = new javax.swing.ImageIcon(getClass().getResource("/ImagesDado/dado"+i+".png"));
    }
    
    public void movimentaPeça(JLabel peaoClicado, Peça peça, int qtdCasasParaAndar ){

        if(qtdCasasParaAndar == 0)
            return;
        
        peaoClicado.setLocation(peça.mover(qtdCasasParaAndar));
       // System.out.println("x: "+peça.mover(qtdCasasParaAndar).x+" y:"+peça.mover(qtdCasasParaAndar).y);
        
        control.proximoJogadorDaVez();
        atualizaView();
     
    }
   
    public int qtdCasasParaAndar(){
        
        int qtdCasasParaAndar = 0; 
        
        
        if(jBtnDado1.isSelected() && jBtnDado2.isSelected()){
            qtdCasasParaAndar = Tabuleiro.getNumDadoUm()+Tabuleiro.getNumDadoDois();
        }
          
        else if (jBtnDado1.isSelected()) {
            qtdCasasParaAndar = Tabuleiro.getNumDadoUm();
        }
           
        else if(jBtnDado2.isSelected()){
            qtdCasasParaAndar = Tabuleiro.getNumDadoDois();
        }
       
        return qtdCasasParaAndar;
    }
    
    private void atualizaView() {
        
        switch(control.getCorDoJogadorDaVez()){
            
            case AMARELO:   updatePositionDados(new Point(300,400),new Point(350,400)); 
                           // jLabelAmarelo.setText("Andou "+qtdCasasParaAndar+" casas");
                            break;
            case VERDE:     updatePositionDados(new Point(290,20),new Point(340,20));
                            //Peca P = retornaPecaAleatoriamente();
                            //JLabel l = retornaLabelAleatoriamente();
                            // maquinaEscolha(l,P);
                            
                            changeButtonLayout(jBtnDado1,false);
                            changeButtonLayout(jBtnDado2,false);
                            
                            maquinaEscolha(jLabelPeaoGreen1,control.getJogadorDaVez().getPeça(0),"Verde");                    
                            break;
            case VERMELHO:  updatePositionDados(new Point(880,20),new Point(880,70));
            
                            changeButtonLayout(jBtnDado1,false);
                            changeButtonLayout(jBtnDado2,false);
                            
                            maquinaEscolha(jLabelPeaoRed1,control.getJogadorDaVez().getPeça(0),"Vermelho");    
                            break;
            case AZUL:      updatePositionDados(new Point(830,610),new Point(880,610));
            
                            changeButtonLayout(jBtnDado1,false);
                            changeButtonLayout(jBtnDado2,false);
            
                            maquinaEscolha(jLabelPeaoBlue1,control.getJogadorDaVez().getPeça(0),"Azul");  
                            break;
        }
  
    }

    private void updatePositionDados(Point PosBtn1, Point PosBtn2) {
         jBtnDado1.setLocation(PosBtn1);
         jBtnDado2.setLocation(PosBtn2); 
    }

    private void maquinaEscolha(JLabel peao, Peça p, String cor) {
       int valorDado;
       
//       timerAnimateDado1.start();
//       timerAnimateDado2.start();
//       
//       long t= System.currentTimeMillis();
//       long end = t+5000;
//       while(System.currentTimeMillis() < end) {
//           
//       }
      movimentaDado.start(EnumDado.Ambos);
   
       int escolha = control.escolhaMaquina();
     
       JOptionPane.showMessageDialog(this, "Vez de jogada do "+cor+"!");
        
        switch(escolha){
            case 1: //timerAnimateDado1.stop();
                    //timerAnimateDado2.stop();
                    movimentaDado.stop(EnumDado.Ambos);
                    changeButtonLayout(jBtnDado1,true);
                    
                    valorDado = Tabuleiro.getNumDadoUm();
                    jBtnDado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesDado/dado"+valorDado+".png")));
                    JOptionPane.showMessageDialog(this, "O jogador "+cor+" já fez sua escolha !");
                    movimentaPeça(peao,p,qtdCasasParaAndar());
                    
                    break;
            case 2: 
                    //timerAnimateDado1.stop();
                    //timerAnimateDado2.stop();
                     movimentaDado.stop(EnumDado.Ambos);
                    changeButtonLayout(jBtnDado2,true);
                    
                    valorDado = Tabuleiro.getNumDadoDois();
                    jBtnDado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesDado/dado"+valorDado+".png")));
                    JOptionPane.showMessageDialog(this, "O jogador "+cor+" já fez sua escolha !");
                    movimentaPeça(peao,p,qtdCasasParaAndar());
                    break;
            case 3: //timerAnimateDado1.stop();
                    //timerAnimateDado2.stop();
                     movimentaDado.stop(EnumDado.Ambos);
                    changeButtonLayout(jBtnDado1,true);
                    changeButtonLayout(jBtnDado2,true);
                    
                    valorDado = Tabuleiro.getNumDadoUm();
                    int valorDado2 = Tabuleiro.getNumDadoDois();
                    jBtnDado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesDado/dado"+valorDado+".png")));
                    jBtnDado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesDado/dado"+valorDado2+".png")));
                    JOptionPane.showMessageDialog(this, "O jogador "+cor+" já fez sua escolha !");   
                    movimentaPeça(peao,p,qtdCasasParaAndar());
        }
    } 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jBtnDado1;
    private javax.swing.JToggleButton jBtnDado2;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabelAmarelo;
    private javax.swing.JLabel jLabelAzul;
    private javax.swing.JLabel jLabelCircleBlue2;
    private javax.swing.JLabel jLabelCircleGreen2;
    private javax.swing.JLabel jLabelCircleRed2;
    private javax.swing.JLabel jLabelCircleYellow2;
    private javax.swing.JLabel jLabelPeaoBlue1;
    private javax.swing.JLabel jLabelPeaoBlue2;
    private javax.swing.JLabel jLabelPeaoBlue3;
    private javax.swing.JLabel jLabelPeaoBlue4;
    private javax.swing.JLabel jLabelPeaoGreen1;
    private javax.swing.JLabel jLabelPeaoGreen2;
    private javax.swing.JLabel jLabelPeaoGreen3;
    private javax.swing.JLabel jLabelPeaoGreen4;
    private javax.swing.JLabel jLabelPeaoRed1;
    private javax.swing.JLabel jLabelPeaoRed2;
    private javax.swing.JLabel jLabelPeaoRed3;
    private javax.swing.JLabel jLabelPeaoRed4;
    private javax.swing.JLabel jLabelPeaoYellow1;
    private javax.swing.JLabel jLabelPeaoYellow2;
    private javax.swing.JLabel jLabelPeaoYellow3;
    private javax.swing.JLabel jLabelPeaoYellow4;
    private javax.swing.JLabel jLabelTabuleiero2;
    private javax.swing.JLabel jLabelUser10;
    private javax.swing.JLabel jLabelUser11;
    private javax.swing.JLabel jLabelUser12;
    private javax.swing.JLabel jLabelUser9;
    private javax.swing.JLabel jLabelVerde;
    private javax.swing.JLabel jLabelVermelho;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}       
       
    

