/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author paabl
 */
public class TabuleiroVIew2 extends javax.swing.JPanel {

    /**
     * Creates new form TabuleiroVIew2
     */
    public TabuleiroVIew2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPeaoGreen2 = new javax.swing.JLabel();
        jLabelTabuleiro = new javax.swing.JLabel();
        Dado = new javax.swing.JLabel();
        Dado1 = new javax.swing.JLabel();
        Dado2 = new javax.swing.JLabel();
        Dado3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(950, 950));
        setLayout(null);

        jLabelPeaoGreen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePinos/ludo-piece-green-th.png"))); // NOI18N
        jLabelPeaoGreen2.setText("0");
        add(jLabelPeaoGreen2);
        jLabelPeaoGreen2.setBounds(350, 130, 30, 42);

        jLabelTabuleiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageTabuleiro/tabu.png"))); // NOI18N
        jLabelTabuleiro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        add(jLabelTabuleiro);
        jLabelTabuleiro.setBounds(280, 0, 650, 650);

        Dado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageTabuleiro/dado.png"))); // NOI18N
        add(Dado);
        Dado.setBounds(970, 0, 115, 87);

        Dado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageTabuleiro/dado.png"))); // NOI18N
        add(Dado1);
        Dado1.setBounds(120, 0, 115, 87);

        Dado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageTabuleiro/dado.png"))); // NOI18N
        add(Dado2);
        Dado2.setBounds(110, 550, 115, 87);

        Dado3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageTabuleiro/dado.png"))); // NOI18N
        add(Dado3);
        Dado3.setBounds(990, 560, 115, 87);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageTabuleiro/yellow-circle-design-hi.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 340, 350, 350);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageTabuleiro/blue-circle-design-hi.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(870, 330, 350, 350);

        jLabel3.setForeground(new java.awt.Color(128, 128, 128));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageTabuleiro/green-circle-design-hi.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(0, -30, 350, 350);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageTabuleiro/red-circle-design-hi.png"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(840, -40, 350, 350);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dado;
    private javax.swing.JLabel Dado1;
    private javax.swing.JLabel Dado2;
    private javax.swing.JLabel Dado3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelPeaoGreen2;
    private javax.swing.JLabel jLabelTabuleiro;
    // End of variables declaration//GEN-END:variables
}
